import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";

export const metadata: Metadata = {
  title: "The Newspaper App",
  description: "The Newspaper App Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="border bottom-2">
          <Navbar />
        </div>
        <div className="container mx-auto">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
