import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import { UserProvider } from "@/components/context/userContext";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "The Newspaper App",
  description: "The Newspaper App Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <div className="border bottom-2">
            <Navbar />
          </div>
          <div className="container mx-auto">
            <Toaster />
            {children}
          </div>
          {/* <Footer /> */}
        </UserProvider>
      </body>
    </html>
  );
}
